DROP INDEX IF EXISTS idx_membership_number;
DROP TABLE IF EXISTS Member;
DROP SEQUENCE IF EXISTS MEMBER_SEQ;

CREATE TABLE Member (
  ID INTEGER NOT NULL ,
  MEMBERSHIP_NUMBER VARCHAR(256) NOT NULL,
  FIRST_NAME VARCHAR(256) NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  NICK_NAME VARCHAR(256) NOT NULL,
  GENDER_ROLE VARCHAR(256) NOT NULL,
  SEX VARCHAR(256) NOT NULL,
  LENGTH SMALLINT,
  WEIGHT SMALLINT,
  CREATED_ON TIMESTAMP NULL DEFAULT NULL,
  LASTMODIFIED_ON TIMESTAMP NULL DEFAULT NULL,
  VERSION BIGINT,
  PRIMARY KEY(ID)
);

CREATE UNIQUE INDEX idx_membership_number ON Member (MEMBERSHIP_NUMBER);

CREATE SEQUENCE MEMBER_SEQ START WITH 1;