DROP TABLE IF EXISTS Member;
DROP SEQUENCE IF EXISTS MEMBER_SEQ;


CREATE TABLE Member (
  ID INTEGER NOT NULL ,
  MEMBERSHIP_NUMBER VARCHAR(256) NOT NULL,
  FIRST_NAME VARCHAR(256) NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  NICK_NAME VARCHAR(256) NOT NULL,
  GENDER_ROLE VARCHAR(256) NOT NULL,
  SEX VARCHAR(256) NOT NULL,
  LENGTH SMALLINT,
  WEIGHT SMALLINT,
  CREATED_ON TIMESTAMP NULL DEFAULT NULL,
  LASTMODIFIED_ON TIMESTAMP NULL DEFAULT NULL,
  VERSION BIGINT,
  PRIMARY KEY(ID),
  UNIQUE (MEMBERSHIP_NUMBER)
);

CREATE SEQUENCE MEMBER_SEQ START WITH 1;

DROP TABLE IF EXISTS Geographical_Data;
DROP SEQUENCE IF EXISTS GEO_DATA_SEQ;

CREATE TABLE Geographical_Data (
  ID INTEGER NOT NULL ,
  ZIPCODE VARCHAR(60),
  MUNICIPALITY VARCHAR(256),
  PROVINCE VARCHAR(256),
  COUNTRY VARCHAR(256),
  FLAG BYTEA,
  VERSION BIGINT,
  CREATED_ON TIMESTAMP NULL DEFAULT NULL,
  LASTMODIFIED_ON TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY(ID)
);

CREATE INDEX idx_geo_data_zipcode ON GEOGRAPHICAL_DATA (ZIPCODE);
CREATE INDEX idx_geo_data_municipality ON GEOGRAPHICAL_DATA (MUNICIPALITY);
CREATE INDEX idx_geo_data_province ON GEOGRAPHICAL_DATA (PROVINCE);

CREATE SEQUENCE GEO_DATA_SEQ START WITH 1;

DROP TABLE IF EXISTS Country;

CREATE TABLE Country (
  ID INTEGER NOT NULL ,
  NAME VARCHAR(256),
  FLAG BYTEA,
  VERSION BIGINT,
  CREATED_ON TIMESTAMP NULL DEFAULT NULL,
  LASTMODIFIED_ON TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY(ID)
);

insert into Country(id, name, flag)
values(1, 'BELGIUM', (select bytea_import('/home/peterdp/Desktop/flag_belgium.png')));
